export default [
    {
        name:"台北市",
        enName:"Taipei"
    },
    {
        name:"基隆市",
        enName:"Keelung",
    },
    {
        name:"新北市",
        enName:"NewTaipei",
    },
    {
        name:"桃園市",
        enName:"Taoyuan",
    },
    {
        name:"宜蘭縣",
        enName:"YilanCounty",
    },
    {
        name:"新竹市",
        enName:"Hsinchu"
    },
    {
        name:"新竹縣",
        enName:"HsinchuCounty",
    },
    {
        name:"苗栗縣",
        enName:"MiaoliCounty",
    },
    {
        name:"台中市",
        enName:"Taichung",
    },
    {
        name:"彰化縣",
        enName:"ChanghuaCounty",
    },
    {
        name:"南投縣",
        enName:"NantouCounty",
    },
    {
        name:"嘉義市",
        enName:"Chiayi",
    },
    {
        name:"嘉義縣",
        enName:"ChiayiCounty",
    },
    {
        name:"雲林縣",
        enName:"YunlinCounty",
    },
    {
        name:"台南市",
        enName:"Tainan",
    },
    {
        name:"高雄市",
        enName:"Kaohsiung",
    },
    
    {
        name:"屏東縣",
        enName:"PingtungCounty",
    },
    {
        name:"花蓮縣",
        enName:"HualienCounty",
    },
    {
        name:"台東縣",
        enName:"TaitungCounty",
    },
    {
        name:"連江縣",
        enName:"LienchiangCounty",
    },
    {
        name:"澎湖縣",
        enName:"PenghuCounty",
    },
    {
        name:"金門縣",
        enName:"KinmenCounty",
    },
]